version: '3.8'

x-postgres-env: &postgres-env
    POSTGRES_USER: test_user
    POSTGRES_DB: test_user
    POSTGRES_PASSWORD: test_password

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        <<: *postgres-env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d test_user -U test_user"]
        interval: 5s
        timeout: 3s
        start_period: 5s
        retries: 3

  app:
    depends_on:
        postgres:
            condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    command: go run cmd/pepper/main.go
    volumes:
      - .:/app
    environment:
      <<: [
          *postgres-env
        ]
      ENVIRONMENT: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_SSL_MODE: 'false'

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes_from:
      - app
    command: ["-path", "app/pkg/migrations", "-database",  "postgres://test_user:test_password@postgres:5432/test_user?sslmode=disable", "up"]
