name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run:  docker-compose -f docker-compose.yml up -d

    - name: Run Tests in app service
      run: docker-compose -f docker-compose.yml exec pepper_app_1 go test -v ./tests
